version: 2.1

jobs:
  tests_and_linters:
    docker:
      - image: "cimg/ruby:3.4.2"
    environment:
      COVERAGE: "false"
      RACK_ENV: test
      RAILS_ENV: test
    parallelism: 1
    resource_class: medium
    steps:
      - checkout
      - ruby/install-deps:
          key: gems-v6
          include-branch-in-cache-key: false
      - run:
          name: "Rubocop"
          command: "bundle exec rake rubocop"
      - run:
          name: "Minitest"
          command: "bundle exec rake test"
      - store_artifacts:
          path: /tmp/rspec/
          destination: rspec
      - store_test_results:
          path: /tmp/rspec/

orbs:
  ruby: circleci/ruby@2.1

workflows:
  version: 2
  test:
    jobs:
      - tests_and_linters
